"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""

pentagonal_set = set()
hexagonal_set = set()


def add_in_sets(n):
    pentagonal_set.add(n * (3 * n - 1) // 2)
    hexagonal_set.add(n * (2 * n - 1))


def triangle(n):
    return n * (n + 1) // 2


def counting(i=286):
    while 1:
        yield i
        i += 1


def find():
    for i in counting():
        current = triangle(i)
        if current in pentagonal_set and current in hexagonal_set:
            print(i)
            return current

        add_in_sets(i)


print(find())
